### ISSUE TITLE
paddle静态图转动态图报错

### ISSUE THREAD

**Issue by LitianD** [LKKlein/PaddleTools#3]
Traceback (most recent call last):
  File "trans_dynamic.py", line 3, in <module>
    static2dynamic(params_dir="./assets/params/", save_path="./dy_params")
  File "/home/LAB/r-zhanglt/anaconda3/lib/python3.7/site-packages/paddletools/checkpoints.py", line 65, in static2dynamic
    data, data_type, lod_info = _read_static_params(param_path)
  File "/home/LAB/r-zhanglt/anaconda3/lib/python3.7/site-packages/paddletools/checkpoints.py", line 33, in _read_static_params
    buf = struct.unpack("c" * buf_size, f.read(buf_size))

**Comment by LKKlein** [comment]
能把全部报错内容贴一下吗？应该下面还有一段吧。

这里提供的转换中，静态图是指解压tar文件后的文件夹，不知你有没有输入错误呢？

如果输入确认没问题，那方便的话，能不能把静态图的参数文件提供一下呢？
