### ISSUE TITLE
命令行和代码模式都报内存错误

### ISSUE THREAD

**Issue by jasonlbx13** [LKKlein/PaddleTools#5]
[2021-02-24 19:44:18,704] [    INFO] - found 5 parameters. start to read.
Traceback (most recent call last):
  File "/home/data/miniconda3/envs/paddle/bin/pdtools", line 8, in <module>
    sys.exit(main())
  File "/home/data/miniconda3/envs/paddle/lib/python3.6/site-packages/paddletools/control.py", line 37, in main
    static2dynamic(params_dir=cmd_args["--src"], save_path=cmd_args["--dst"])
  File "/home/data/miniconda3/envs/paddle/lib/python3.6/site-packages/paddletools/checkpoints.py", line 65, in static2dynamic
    data, data_type, lod_info = _read_static_params(param_path)
  File "/home/data/miniconda3/envs/paddle/lib/python3.6/site-packages/paddletools/checkpoints.py", line 33, in _read_static_params
    buf = struct.unpack("c" * buf_size, f.read(buf_size))
MemoryError

ubuntu16.04
python3.6 CUDA10.0 paddle2.0
内存16G
显卡1660ti

**Comment by LKKlein** [comment]
这个工具是在Paddle1.6 - 1.8版本中测试的，2.0的paddle还没有测试过，可能存在兼容问题
