### ISSUE TITLE
静态图转动态图时出错

### ISSUE THREAD

**Issue by zwboss** [LKKlein/PaddleTools#7]
静态图转动态图时出现如下报错，是为啥呢
`Traceback (most recent call last):
   File "change.py", line 4, in <module>
    static2dynamic(params_dir="params/", save_path="params")
   File "/home/disk2/hanzhao/anaconda3/lib/python3.7/site-packages/paddletools/checkpoints.py", line 65, in static2dynamic
    data, data_type, lod_info = _read_static_params(param_path)
   File "/home/disk2/hanzhao/anaconda3/lib/python3.7/site-packages/paddletools/checkpoints.py", line 33, in _read_static_params
    buf = struct.unpack("c" * buf_size, f.read(buf_size))
struct.error: unpack requires a buffer of 1634089506 bytes`

**Comment by LKKlein** [comment]
请问你的paddle版本是多少呢？我这个还没有支持paddlepaddle2.0+版本

**Comment by zwboss** [comment]
> 请问你的paddle版本是多少呢？我这个还没有支持paddlepaddle2.0+版本

是1.6版本的

**Comment by cucumberpieces** [comment]
我也遇到了这个问题，paddle版本是1.8.
